import { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "en" | "gu" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Navbar
    "nav.features": "Features",
    "nav.howItWorks": "How It Works",
    "nav.pricing": "Pricing",
    "nav.languages": "Languages",
    "nav.login": "Log In",
    "nav.startTrial": "Start Free Trial",
    
    // Dashboard Nav
    "nav.dashboard": "Dashboard",
    "nav.customers": "Customers",
    "nav.orders": "Orders",
    "nav.online": "Online",
    "nav.offline": "Offline",
    
    // Dashboard
    "dashboard.welcome": "Welcome to",
    "dashboard.subtitle": "Streamline your tailoring business with instant customer lookup, measurements, and order management.",
    "dashboard.searchPlaceholder": "Quick search: Enter mobile number or customer name...",
    "dashboard.customers": "Customers",
    "dashboard.measurements": "Measurements",
    "dashboard.orders": "Orders",
    "dashboard.revenue": "Revenue",
    "dashboard.newCustomer": "New Customer",
    "dashboard.allCustomers": "All Customers",
    "dashboard.allOrders": "All Orders",
    "dashboard.pendingOrders": "Pending Orders",
    "dashboard.readyForPickup": "Ready for Pickup",
    "dashboard.outstandingBalance": "Outstanding Balance",
    "dashboard.upcomingDeliveries": "Upcoming Deliveries",
    "dashboard.recentOrders": "Recent Orders",
    "dashboard.viewAll": "View All",
    "dashboard.noPendingOrders": "No pending orders",
    "dashboard.noOrders": "No orders yet. Create your first order!",
    
    // Customers Page
    "customers.title": "Customers",
    "customers.totalCustomers": "total customers",
    "customers.addCustomer": "Add Customer",
    "customers.filterPlaceholder": "Filter by name, mobile, or tag...",
    "customers.name": "Name",
    "customers.date": "Date",
    "customers.noCustomersFound": "No Customers Found",
    "customers.adjustSearch": "Try adjusting your search criteria",
    "customers.addFirst": "Start by adding your first customer",
    
    // Customer Detail
    "customerDetail.notFound": "Customer Not Found",
    "customerDetail.notFoundDesc": "The customer you're looking for doesn't exist.",
    "customerDetail.goToCustomers": "Go to Customers",
    "customerDetail.back": "Back to Customers",
    "customerDetail.edit": "Edit",
    "customerDetail.delete": "Delete",
    "customerDetail.deleteTitle": "Delete Customer?",
    "customerDetail.deleteDesc": "This will permanently delete {name} and all their measurements and orders. This action cannot be undone.",
    "customerDetail.cancel": "Cancel",
    "customerDetail.customerSince": "Customer since",
    "customerDetail.measurements": "Measurements",
    "customerDetail.orders": "Orders",
    "customerDetail.totalValue": "Total Value",
    "customerDetail.addMeasurement": "Add Measurement",
    "customerDetail.noMeasurementsYet": "No Measurements Yet",
    "customerDetail.addFirstMeasurement": "Add the first measurement for this customer",
    "customerDetail.createOrder": "Create Order",
    "customerDetail.noOrdersYet": "No Orders Yet",
    "customerDetail.createFirstOrder": "Create the first order for this customer",
    
    // Customer Form
    "customerForm.back": "Back",
    "customerForm.newCustomer": "New Customer",
    "customerForm.editCustomer": "Edit Customer",
    "customerForm.name": "Name",
    "customerForm.nameRequired": "Name *",
    "customerForm.enterName": "Enter customer name",
    "customerForm.mobile": "Mobile Number",
    "customerForm.mobileRequired": "Mobile Number *",
    "customerForm.enterMobile": "Enter 10-digit mobile",
    "customerForm.duplicateWarning": "Customer \"{name}\" already exists with this number",
    "customerForm.email": "Email",
    "customerForm.enterEmail": "Enter email address",
    "customerForm.customerType": "Customer Type",
    "customerForm.vip": "VIP",
    "customerForm.regular": "Regular",
    "customerForm.walkin": "Walk-in",
    "customerForm.address": "Address",
    "customerForm.enterAddress": "Enter full address",
    "customerForm.notes": "Notes",
    "customerForm.enterNotes": "Any special instructions or preferences",
    "customerForm.cancel": "Cancel",
    "customerForm.save": "Save Customer",
    "customerForm.update": "Update Customer",
    "customerForm.nameError": "Please enter customer name",
    "customerForm.mobileError": "Please enter a valid mobile number",
    "customerForm.duplicateError": "A customer with this mobile number already exists",
    "customerForm.addedSuccess": "Customer added successfully",
    "customerForm.updatedSuccess": "Customer updated successfully",
    
    // Customer Search
    "customerSearch.placeholder": "Search by mobile number or name...",
    "customerSearch.noCustomersFound": "No customers found",
    "customerSearch.addNewCustomer": "Add New Customer",
    
    // Orders Page
    "orders.title": "Orders",
    "orders.totalOrders": "total orders",
    "orders.all": "All",
    "orders.pending": "Pending",
    "orders.cutting": "Cutting",
    "orders.stitching": "Stitching",
    "orders.trial": "Trial",
    "orders.ready": "Ready",
    "orders.delivered": "Delivered",
    "orders.cancelled": "Cancelled",
    "orders.searchPlaceholder": "Search by order number or customer...",
    "orders.allPayments": "All Payments",
    "orders.unpaid": "Unpaid",
    "orders.partial": "Partial",
    "orders.paid": "Paid",
    "orders.noOrdersFound": "No Orders Found",
    "orders.adjustFilters": "Try adjusting your filters",
    "orders.createFromCustomers": "Create orders from customer profiles",
    "orders.goToCustomers": "Go to Customers",
    
    // Order Detail
    "orderDetail.notFound": "Order Not Found",
    "orderDetail.notFoundDesc": "The order you're looking for doesn't exist.",
    "orderDetail.goToOrders": "Go to Orders",
    "orderDetail.back": "Back to Orders",
    "orderDetail.order": "Order",
    "orderDetail.createdOn": "Created on",
    "orderDetail.edit": "Edit",
    "orderDetail.cancel": "Cancel",
    "orderDetail.printInvoice": "Print Invoice",
    "orderDetail.customerDetails": "Customer Details",
    "orderDetail.viewProfile": "View Profile",
    "orderDetail.orderItems": "Order Items",
    "orderDetail.total": "Total",
    "orderDetail.orderStatus": "Order Status",
    "orderDetail.status": "Status",
    "orderDetail.deliveryDate": "Delivery Date",
    "orderDetail.urgency": "Urgency",
    "orderDetail.normal": "Normal",
    "orderDetail.urgent": "Urgent",
    "orderDetail.express": "Express",
    "orderDetail.paidAmount": "Paid Amount",
    "orderDetail.saveChanges": "Save Changes",
    "orderDetail.payment": "Payment",
    "orderDetail.balance": "Balance",
    "orderDetail.fullyPaid": "Fully Paid",
    "orderDetail.partiallyPaid": "Partially Paid",
    "orderDetail.orderUpdated": "Order updated",
    "orderDetail.shareWhatsApp": "Share via WhatsApp",
    "orderDetail.whatsappOpened": "Opening WhatsApp...",
    
    // Order Form
    "orderForm.newOrder": "New Order",
    "orderForm.editOrder": "Edit Order",
    "orderForm.orderItems": "Order Items",
    "orderForm.addItem": "Add Item",
    "orderForm.garmentType": "Garment Type",
    "orderForm.shirt": "Shirt",
    "orderForm.pant": "Pant",
    "orderForm.kurta": "Kurta",
    "orderForm.koti": "Koti",
    "orderForm.waistcoat": "Waistcoat",
    "orderForm.qty": "Qty",
    "orderForm.price": "Price",
    "orderForm.urgencyLevel": "Urgency Level",
    "orderForm.normal7days": "Normal (7 days)",
    "orderForm.urgent3days": "Urgent (3 days) +25%",
    "orderForm.express1day": "Express (1 day) +50%",
    "orderForm.deliveryDate": "Delivery Date",
    "orderForm.totalAmount": "Total Amount",
    "orderForm.advancePayment": "Advance Payment",
    "orderForm.orderNotes": "Order Notes",
    "orderForm.notesPlaceholder": "Any special instructions for this order...",
    "orderForm.cancel": "Cancel",
    "orderForm.createOrder": "Create Order",
    "orderForm.updateOrder": "Update Order",
    "orderForm.itemError": "Please add at least one item",
    "orderForm.createdSuccess": "Order #{number} created",
    "orderForm.updatedSuccess": "Order updated successfully",
    "orderForm.measurements": "Measurements",
    
    // Order Card
    "orderCard.delivery": "Delivery",
    "orderCard.balance": "Balance",
    "orderCard.view": "View",
    "orderCard.edit": "Edit",
    
    // Measurement Form
    "measurementForm.newMeasurement": "New Measurement",
    "measurementForm.editMeasurement": "Edit Measurement",
    "measurementForm.copyPrevious": "Copy Previous",
    "measurementForm.shirt": "Shirt",
    "measurementForm.pant": "Pant",
    "measurementForm.kurta": "Kurta",
    "measurementForm.koti": "Koti",
    "measurementForm.waistcoat": "Waistcoat",
    "measurementForm.length": "Length",
    "measurementForm.chest": "Chest",
    "measurementForm.waist": "Waist",
    "measurementForm.shoulder": "Shoulder",
    "measurementForm.sleeveLength": "Sleeve Length",
    "measurementForm.sleeveOpening": "Sleeve Opening",
    "measurementForm.collar": "Collar",
    "measurementForm.armHole": "Arm Hole",
    "measurementForm.cuffSize": "Cuff Size",
    "measurementForm.frontChest": "Front Chest",
    "measurementForm.backWidth": "Back Width",
    "measurementForm.hip": "Hip",
    "measurementForm.thigh": "Thigh",
    "measurementForm.knee": "Knee",
    "measurementForm.bottom": "Bottom",
    "measurementForm.crotch": "Crotch",
    "measurementForm.rise": "Rise",
    "measurementForm.inseam": "Inseam",
    "measurementForm.slit": "Slit",
    "measurementForm.daaman": "Daaman",
    "measurementForm.frontOpening": "Front Opening",
    "measurementForm.frontLength": "Front Length",
    "measurementForm.backLength": "Back Length",
    "measurementForm.notes": "Notes / Special Instructions",
    "measurementForm.notesPlaceholder": "Add any special tailoring instructions or notes...",
    "measurementForm.cancel": "Cancel",
    "measurementForm.save": "Save Measurement",
    "measurementForm.copiedSuccess": "Copied from previous measurement",
    "measurementForm.noPrevious": "No previous measurement found for this type",
    "measurementForm.savedSuccess": "Measurement saved",
    "measurementForm.updatedSuccess": "Measurement updated",
    
    // Measurement Card
    "measurementCard.edit": "Edit",
    "measurementCard.delete": "Delete",
    "measurementCard.deletedSuccess": "Measurement deleted",
    
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.back": "Back",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.customerDeleted": "Customer deleted",
    
    // Hero
    "hero.badge": "Built for Surat's Tailoring Industry",
    "hero.title1": "Manage Your",
    "hero.title2": "Tailoring Business",
    "hero.title3": "Like Never Before",
    "hero.subtitle": "The complete software solution for modern tailors. Customer management, measurements, orders, and billing — all in one place.",
    "hero.available": "Available in ગુજરાતી, हिंदी & English",
    "hero.startTrial": "Start Free Trial",
    "hero.watchDemo": "Watch Demo",
    "hero.stat1Value": "5,000+",
    "hero.stat1Label": "Tailors Trust Us",
    "hero.stat2Value": "2 Min",
    "hero.stat2Label": "Per Order",
    "hero.stat3Value": "100%",
    "hero.stat3Label": "Offline Ready",
    "hero.worksOffline": "Works Offline",
    "hero.noInternet": "No internet needed",
    
    // Features
    "features.badge": "Features",
    "features.title": "Everything You Need to",
    "features.titleHighlight": " Grow Your Business",
    "features.subtitle": "Replace notebooks and registers with simple, icon-driven digital tools. Designed for tailors with any level of tech experience.",
    "features.customer": "Instant Customer Lookup",
    "features.customerDesc": "Find any customer instantly by mobile number. Complete history, measurements, and orders at your fingertips.",
    "features.measurements": "Smart Measurements",
    "features.measurementsDesc": "Templates for Shirt, Pant, Kurta, Koti & more. Auto-populate from previous orders. Never lose measurements.",
    "features.orders": "Visual Order Tracking",
    "features.ordersDesc": "Track every order through stages: Cutting → Stitching → Trial → Ready. Status updates at a glance.",
    "features.billing": "WhatsApp Billing",
    "features.billingDesc": "Generate bills in seconds and share instantly via WhatsApp. No more manual calculations or paper bills.",
    "features.offline": "Works Offline",
    "features.languages": "Languages",
    "features.whatsapp": "WhatsApp Bills",
    "features.alerts": "Delivery Alerts",
    "features.reports": "Daily Reports",
    "features.payments": "Payment Tracking",
    "features.mobile": "Mobile Friendly",
    "features.sync": "Auto Sync",
    "features.more": "And Much More...",
    
    // Workflow
    "workflow.badge": "How It Works",
    "workflow.title": "Traditional vs.",
    "workflow.titleHighlight": " Digital Way",
    "workflow.subtitle": "See how much time you can save every single day",
    "workflow.traditional": "Traditional Method",
    "workflow.software": "With StyleSavvy",
    "workflow.t1Step": "Customer comes",
    "workflow.t1Issue": "Find old notebook",
    "workflow.t2Step": "Search measurements",
    "workflow.t2Issue": "Flip through pages",
    "workflow.t3Step": "Write new order",
    "workflow.t3Issue": "Multiple registers",
    "workflow.t4Step": "Calculate bill",
    "workflow.t4Issue": "Manual calculation",
    "workflow.t5Step": "Track delivery",
    "workflow.t5Issue": "Check all pages",
    "workflow.s1Step": "Enter mobile number",
    "workflow.s1Benefit": "Instant search",
    "workflow.s2Step": "View all measurements",
    "workflow.s2Benefit": "Auto-loads",
    "workflow.s3Step": "Create order",
    "workflow.s3Benefit": "One screen",
    "workflow.s4Step": "Generate bill",
    "workflow.s4Benefit": "Auto-calculated",
    "workflow.s5Step": "Track status",
    "workflow.s5Benefit": "Dashboard view",
    "workflow.traditionalTime": "16-21 min",
    "workflow.softwareTime": "Under 2 min",
    "workflow.perCustomer": "per customer (average)",
    "workflow.saveUp": "Save up to",
    "workflow.saveHours": "3+ Hours",
    "workflow.everyDay": "Every day with",
    "workflow.customers": "20 Customers",
    
    // Pricing
    "pricing.badge": "Pricing",
    "pricing.title": "Simple, Transparent",
    "pricing.titleHighlight": " Pricing",
    "pricing.subtitle": "Start free, upgrade when you need more. No hidden charges.",
    "pricing.free": "Free",
    "pricing.basic": "Basic",
    "pricing.professional": "Professional",
    "pricing.forever": "forever",
    "pricing.month": "/month",
    "pricing.freeDesc": "Perfect to try before you buy",
    "pricing.basicDesc": "For growing tailoring shops",
    "pricing.proDesc": "For established businesses",
    "pricing.getStarted": "Get Started",
    "pricing.startTrial": "Start Free Trial",
    "pricing.mostPopular": "Most Popular",
    "pricing.freeF1": "Up to 50 customers",
    "pricing.freeF2": "Basic measurements",
    "pricing.freeF3": "Local storage only",
    "pricing.freeF4": "Single device",
    "pricing.basicF1": "Unlimited customers",
    "pricing.basicF2": "All measurement templates",
    "pricing.basicF3": "Cloud backup",
    "pricing.basicF4": "WhatsApp integration",
    "pricing.basicF5": "2 devices",
    "pricing.basicF6": "Email support",
    "pricing.proF1": "Everything in Basic",
    "pricing.proF2": "Multiple workers",
    "pricing.proF3": "SMS notifications",
    "pricing.proF4": "Advanced reports",
    "pricing.proF5": "5 devices",
    "pricing.proF6": "Priority support",
    "pricing.proF7": "Worker wage tracking",
    "pricing.oneTime": "Prefer One-Time Payment?",
    "pricing.lifetime": "Get lifetime access for just",
    "pricing.lifetimePrice": "₹9,999",
    "pricing.noMonthly": "(no monthly fees!)",
    "pricing.learnMore": "Learn More About Lifetime Deal",
    
    // Languages Section
    "lang.badge": "Multi-Language Support",
    "lang.title": "Use in Your Own",
    "lang.titleHighlight": "Language",
    "lang.subtitle": "We understand that comfort comes from using software in your mother tongue. That's why StyleSavvy is fully available in Gujarati, Hindi, and English.",
    "lang.feature1": "Complete UI in all 3 languages",
    "lang.feature2": "Measurement labels translated",
    "lang.feature3": "Help & tutorials available",
    "lang.feature4": "Customer support in Gujarati",
    "lang.primary": "Primary",
    "lang.gujarati": "Gujarati",
    "lang.hindi": "Hindi",
    "lang.english": "English",
    "lang.sampleGu": "Easily manage your customers' measurements and orders",
    "lang.sampleHi": "Easily manage your customers' measurements and orders",
    "lang.sampleEn": "Easily manage your customers' measurements and orders",
    
    // CTA
    "cta.title": "Ready to Transform Your",
    "cta.titleHighlight": "Tailoring Business?",
    "cta.subtitle": "Join thousands of tailors in Surat who have already made the switch. Start your free trial today — no credit card required.",
    "cta.trial": "Start 14-Day Free Trial",
    "cta.contact": "Contact Sales",
    "cta.whatsapp": "WhatsApp Support Available",
    
    // Footer
    "footer.tagline": "The complete tailor management software built for modern tailoring businesses in Gujarat and beyond.",
    "footer.taglineGu": "Complete software for Gujarat's tailors",
    "footer.product": "Product",
    "footer.support": "Support",
    "footer.company": "Company",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.howItWorks": "How It Works",
    "footer.downloadApp": "Download App",
    "footer.helpCenter": "Help Center",
    "footer.videoTutorials": "Video Tutorials",
    "footer.contactUs": "Contact Us",
    "footer.whatsappSupport": "WhatsApp Support",
    "footer.aboutUs": "About Us",
    "footer.careers": "Careers",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.rights": "© 2024 StyleSavvy. All rights reserved.",
    "footer.madeWith": "Made with ❤️ for Surat's Tailoring Community",
  },
  gu: {
    // Navbar
    "nav.features": "ફીચર્સ",
    "nav.howItWorks": "કેવી રીતે કામ કરે છે",
    "nav.pricing": "કિંમત",
    "nav.languages": "ભાષાઓ",
    "nav.login": "લૉગ ઇન",
    "nav.startTrial": "મફત ટ્રાયલ શરૂ કરો",
    
    // Dashboard Nav
    "nav.dashboard": "ડેશબોર્ડ",
    "nav.customers": "ગ્રાહકો",
    "nav.orders": "ઓર્ડર",
    "nav.online": "ઓનલાઇન",
    "nav.offline": "ઓફલાઇન",
    
    // Dashboard
    "dashboard.welcome": "સ્વાગત છે",
    "dashboard.subtitle": "ગ્રાહક લુકઅપ, માપ અને ઓર્ડર મેનેજમેન્ટ સાથે તમારા ટેલરિંગ બિઝનેસને સુવ્યવસ્થિત કરો.",
    "dashboard.searchPlaceholder": "ઝડપી શોધ: મોબાઇલ નંબર અથવા ગ્રાહકનું નામ દાખલ કરો...",
    "dashboard.customers": "ગ્રાહકો",
    "dashboard.measurements": "માપ",
    "dashboard.orders": "ઓર્ડર",
    "dashboard.revenue": "આવક",
    "dashboard.newCustomer": "નવો ગ્રાહક",
    "dashboard.allCustomers": "બધા ગ્રાહકો",
    "dashboard.allOrders": "બધા ઓર્ડર",
    "dashboard.pendingOrders": "પેન્ડિંગ ઓર્ડર",
    "dashboard.readyForPickup": "પિકઅપ માટે તૈયાર",
    "dashboard.outstandingBalance": "બાકી રકમ",
    "dashboard.upcomingDeliveries": "આગામી ડિલિવરી",
    "dashboard.recentOrders": "તાજેતરના ઓર્ડર",
    "dashboard.viewAll": "બધું જુઓ",
    "dashboard.noPendingOrders": "કોઈ પેન્ડિંગ ઓર્ડર નથી",
    "dashboard.noOrders": "હજુ સુધી કોઈ ઓર્ડર નથી. તમારો પ્રથમ ઓર્ડર બનાવો!",
    
    // Customers Page
    "customers.title": "ગ્રાહકો",
    "customers.totalCustomers": "કુલ ગ્રાહકો",
    "customers.addCustomer": "ગ્રાહક ઉમેરો",
    "customers.filterPlaceholder": "નામ, મોબાઇલ અથવા ટેગથી ફિલ્ટર કરો...",
    "customers.name": "નામ",
    "customers.date": "તારીખ",
    "customers.noCustomersFound": "કોઈ ગ્રાહકો મળ્યા નથી",
    "customers.adjustSearch": "તમારા શોધ માપદંડને સમાયોજિત કરવાનો પ્રયાસ કરો",
    "customers.addFirst": "તમારા પ્રથમ ગ્રાહક ઉમેરીને શરૂ કરો",
    
    // Customer Detail
    "customerDetail.notFound": "ગ્રાહક મળ્યો નથી",
    "customerDetail.notFoundDesc": "તમે જે ગ્રાહકને શોધી રહ્યા છો તે અસ્તિત્વમાં નથી.",
    "customerDetail.goToCustomers": "ગ્રાહકો પર જાઓ",
    "customerDetail.back": "ગ્રાહકો પર પાછા",
    "customerDetail.edit": "ફેરફાર",
    "customerDetail.delete": "કાઢી નાખો",
    "customerDetail.deleteTitle": "ગ્રાહક કાઢી નાખો?",
    "customerDetail.deleteDesc": "આ {name} અને તેમના બધા માપ અને ઓર્ડર કાયમ માટે કાઢી નાખશે. આ ક્રિયા પૂર્વવત્ કરી શકાતી નથી.",
    "customerDetail.cancel": "રદ કરો",
    "customerDetail.customerSince": "ગ્રાહક ત્યારથી",
    "customerDetail.measurements": "માપ",
    "customerDetail.orders": "ઓર્ડર",
    "customerDetail.totalValue": "કુલ મૂલ્ય",
    "customerDetail.addMeasurement": "માપ ઉમેરો",
    "customerDetail.noMeasurementsYet": "હજુ સુધી કોઈ માપ નથી",
    "customerDetail.addFirstMeasurement": "આ ગ્રાહક માટે પ્રથમ માપ ઉમેરો",
    "customerDetail.createOrder": "ઓર્ડર બનાવો",
    "customerDetail.noOrdersYet": "હજુ સુધી કોઈ ઓર્ડર નથી",
    "customerDetail.createFirstOrder": "આ ગ્રાહક માટે પ્રથમ ઓર્ડર બનાવો",
    
    // Customer Form
    "customerForm.back": "પાછા",
    "customerForm.newCustomer": "નવો ગ્રાહક",
    "customerForm.editCustomer": "ગ્રાહક ફેરફાર",
    "customerForm.name": "નામ",
    "customerForm.nameRequired": "નામ *",
    "customerForm.enterName": "ગ્રાહકનું નામ દાખલ કરો",
    "customerForm.mobile": "મોબાઇલ નંબર",
    "customerForm.mobileRequired": "મોબાઇલ નંબર *",
    "customerForm.enterMobile": "10-અંકનો મોબાઇલ દાખલ કરો",
    "customerForm.duplicateWarning": "આ નંબર સાથે ગ્રાહક \"{name}\" પહેલેથી જ છે",
    "customerForm.email": "ઇમેઇલ",
    "customerForm.enterEmail": "ઇમેઇલ સરનામું દાખલ કરો",
    "customerForm.customerType": "ગ્રાહક પ્રકાર",
    "customerForm.vip": "VIP",
    "customerForm.regular": "રેગ્યુલર",
    "customerForm.walkin": "વોક-ઇન",
    "customerForm.address": "સરનામું",
    "customerForm.enterAddress": "સંપૂર્ણ સરનામું દાખલ કરો",
    "customerForm.notes": "નોંધ",
    "customerForm.enterNotes": "કોઈપણ વિશેષ સૂચનાઓ અથવા પસંદગીઓ",
    "customerForm.cancel": "રદ કરો",
    "customerForm.save": "ગ્રાહક સાચવો",
    "customerForm.update": "ગ્રાહક અપડેટ કરો",
    "customerForm.nameError": "કૃપા કરીને ગ્રાહકનું નામ દાખલ કરો",
    "customerForm.mobileError": "કૃપા કરીને માન્ય મોબાઇલ નંબર દાખલ કરો",
    "customerForm.duplicateError": "આ મોબાઇલ નંબર સાથે ગ્રાહક પહેલેથી છે",
    "customerForm.addedSuccess": "ગ્રાહક સફળતાપૂર્વક ઉમેરાયો",
    "customerForm.updatedSuccess": "ગ્રાહક સફળતાપૂર્વક અપડેટ થયો",
    
    // Customer Search
    "customerSearch.placeholder": "મોબાઇલ નંબર અથવા નામથી શોધો...",
    "customerSearch.noCustomersFound": "કોઈ ગ્રાહકો મળ્યા નથી",
    "customerSearch.addNewCustomer": "નવો ગ્રાહક ઉમેરો",
    
    // Orders Page
    "orders.title": "ઓર્ડર",
    "orders.totalOrders": "કુલ ઓર્ડર",
    "orders.all": "બધા",
    "orders.pending": "પેન્ડિંગ",
    "orders.cutting": "કટિંગ",
    "orders.stitching": "સિલાઈ",
    "orders.trial": "ટ્રાયલ",
    "orders.ready": "તૈયાર",
    "orders.delivered": "ડિલિવર",
    "orders.cancelled": "રદ",
    "orders.searchPlaceholder": "ઓર્ડર નંબર અથવા ગ્રાહક દ્વારા શોધો...",
    "orders.allPayments": "બધી ચુકવણી",
    "orders.unpaid": "અવેતન",
    "orders.partial": "આંશિક",
    "orders.paid": "ચૂકવેલ",
    "orders.noOrdersFound": "કોઈ ઓર્ડર મળ્યા નથી",
    "orders.adjustFilters": "તમારા ફિલ્ટર્સ સમાયોજિત કરવાનો પ્રયાસ કરો",
    "orders.createFromCustomers": "ગ્રાહક પ્રોફાઇલમાંથી ઓર્ડર બનાવો",
    "orders.goToCustomers": "ગ્રાહકો પર જાઓ",
    
    // Order Detail
    "orderDetail.notFound": "ઓર્ડર મળ્યો નથી",
    "orderDetail.notFoundDesc": "તમે જે ઓર્ડર શોધી રહ્યા છો તે અસ્તિત્વમાં નથી.",
    "orderDetail.goToOrders": "ઓર્ડર પર જાઓ",
    "orderDetail.back": "ઓર્ડર પર પાછા",
    "orderDetail.order": "ઓર્ડર",
    "orderDetail.createdOn": "બનાવ્યું",
    "orderDetail.edit": "ફેરફાર",
    "orderDetail.cancel": "રદ કરો",
    "orderDetail.printInvoice": "ઇન્વોઇસ પ્રિન્ટ",
    "orderDetail.customerDetails": "ગ્રાહક વિગતો",
    "orderDetail.viewProfile": "પ્રોફાઇલ જુઓ",
    "orderDetail.orderItems": "ઓર્ડર આઇટમ્સ",
    "orderDetail.total": "કુલ",
    "orderDetail.orderStatus": "ઓર્ડર સ્થિતિ",
    "orderDetail.status": "સ્થિતિ",
    "orderDetail.deliveryDate": "ડિલિવરી તારીખ",
    "orderDetail.urgency": "અર્જન્સી",
    "orderDetail.normal": "સામાન્ય",
    "orderDetail.urgent": "અર્જન્ટ",
    "orderDetail.express": "એક્સપ્રેસ",
    "orderDetail.paidAmount": "ચૂકવેલ રકમ",
    "orderDetail.saveChanges": "ફેરફારો સાચવો",
    "orderDetail.payment": "ચુકવણી",
    "orderDetail.balance": "બાકી",
    "orderDetail.fullyPaid": "સંપૂર્ણ ચૂકવેલ",
    "orderDetail.partiallyPaid": "આંશિક ચૂકવેલ",
    "orderDetail.orderUpdated": "ઓર્ડર અપડેટ થયો",
    "orderDetail.shareWhatsApp": "WhatsApp દ્વારા શેર કરો",
    "orderDetail.whatsappOpened": "WhatsApp ખોલી રહ્યા છીએ...",
    
    // Order Form
    "orderForm.newOrder": "નવો ઓર્ડર",
    "orderForm.editOrder": "ઓર્ડર ફેરફાર",
    "orderForm.orderItems": "ઓર્ડર આઇટમ્સ",
    "orderForm.addItem": "આઇટમ ઉમેરો",
    "orderForm.garmentType": "કપડાનો પ્રકાર",
    "orderForm.shirt": "શર્ટ",
    "orderForm.pant": "પેન્ટ",
    "orderForm.kurta": "કુર્તો",
    "orderForm.koti": "કોટી",
    "orderForm.waistcoat": "વેસ્ટકોટ",
    "orderForm.qty": "જથ્થો",
    "orderForm.price": "કિંમત",
    "orderForm.urgencyLevel": "અર્જન્સી લેવલ",
    "orderForm.normal7days": "સામાન્ય (7 દિવસ)",
    "orderForm.urgent3days": "અર્જન્ટ (3 દિવસ) +25%",
    "orderForm.express1day": "એક્સપ્રેસ (1 દિવસ) +50%",
    "orderForm.deliveryDate": "ડિલિવરી તારીખ",
    "orderForm.totalAmount": "કુલ રકમ",
    "orderForm.advancePayment": "એડવાન્સ ચુકવણી",
    "orderForm.orderNotes": "ઓર્ડર નોંધ",
    "orderForm.notesPlaceholder": "આ ઓર્ડર માટે કોઈ વિશેષ સૂચનાઓ...",
    "orderForm.cancel": "રદ કરો",
    "orderForm.createOrder": "ઓર્ડર બનાવો",
    "orderForm.updateOrder": "ઓર્ડર અપડેટ કરો",
    "orderForm.itemError": "કૃપા કરીને ઓછામાં ઓછી એક આઇટમ ઉમેરો",
    "orderForm.createdSuccess": "ઓર્ડર #{number} બનાવ્યો",
    "orderForm.updatedSuccess": "ઓર્ડર સફળતાપૂર્વક અપડેટ થયો",
    "orderForm.measurements": "માપ",
    
    // Order Card
    "orderCard.delivery": "ડિલિવરી",
    "orderCard.balance": "બાકી",
    "orderCard.view": "જુઓ",
    "orderCard.edit": "ફેરફાર",
    
    // Measurement Form
    "measurementForm.newMeasurement": "નવું માપ",
    "measurementForm.editMeasurement": "માપ ફેરફાર",
    "measurementForm.copyPrevious": "પહેલાનું કોપી",
    "measurementForm.shirt": "શર્ટ",
    "measurementForm.pant": "પેન્ટ",
    "measurementForm.kurta": "કુર્તો",
    "measurementForm.koti": "કોટી",
    "measurementForm.waistcoat": "વેસ્ટકોટ",
    "measurementForm.length": "લંબાઈ",
    "measurementForm.chest": "છાતી",
    "measurementForm.waist": "કમર",
    "measurementForm.shoulder": "ખભો",
    "measurementForm.sleeveLength": "સ્લીવ લંબાઈ",
    "measurementForm.sleeveOpening": "સ્લીવ ઓપનિંગ",
    "measurementForm.collar": "કોલર",
    "measurementForm.armHole": "આર્મ હોલ",
    "measurementForm.cuffSize": "કફ સાઇઝ",
    "measurementForm.frontChest": "ફ્રન્ટ છાતી",
    "measurementForm.backWidth": "પાછળની પહોળાઈ",
    "measurementForm.hip": "હિપ",
    "measurementForm.thigh": "થાઇ",
    "measurementForm.knee": "ઘૂંટણ",
    "measurementForm.bottom": "બોટમ",
    "measurementForm.crotch": "ક્રોચ",
    "measurementForm.rise": "રાઇઝ",
    "measurementForm.inseam": "ઇન્સીમ",
    "measurementForm.slit": "સ્લિટ",
    "measurementForm.daaman": "દામણ",
    "measurementForm.frontOpening": "ફ્રન્ટ ઓપનિંગ",
    "measurementForm.frontLength": "ફ્રન્ટ લંબાઈ",
    "measurementForm.backLength": "પાછળની લંબાઈ",
    "measurementForm.notes": "નોંધ / વિશેષ સૂચનાઓ",
    "measurementForm.notesPlaceholder": "કોઈ વિશેષ ટેલરિંગ સૂચનાઓ અથવા નોંધ ઉમેરો...",
    "measurementForm.cancel": "રદ કરો",
    "measurementForm.save": "માપ સાચવો",
    "measurementForm.copiedSuccess": "પહેલાના માપમાંથી કોપી કર્યું",
    "measurementForm.noPrevious": "આ પ્રકાર માટે કોઈ પહેલાનું માપ મળ્યું નથી",
    "measurementForm.savedSuccess": "માપ સાચવ્યું",
    "measurementForm.updatedSuccess": "માપ અપડેટ થયું",
    
    // Measurement Card
    "measurementCard.edit": "ફેરફાર",
    "measurementCard.delete": "કાઢી નાખો",
    "measurementCard.deletedSuccess": "માપ કાઢી નાખ્યું",
    
    // Common
    "common.save": "સાચવો",
    "common.cancel": "રદ કરો",
    "common.delete": "કાઢી નાખો",
    "common.edit": "ફેરફાર",
    "common.view": "જુઓ",
    "common.back": "પાછા",
    "common.search": "શોધો",
    "common.filter": "ફિલ્ટર",
    "common.loading": "લોડ થઈ રહ્યું છે...",
    "common.error": "ભૂલ",
    "common.success": "સફળ",
    "common.customerDeleted": "ગ્રાહક કાઢી નાખ્યો",
    
    // Hero
    "hero.badge": "સુરતના ટેલરિંગ ઉદ્યોગ માટે બનાવેલ",
    "hero.title1": "તમારો",
    "hero.title2": "ટેલરિંગ બિઝનેસ",
    "hero.title3": "પહેલા ક્યારેય ન હતો એમ મેનેજ કરો",
    "hero.subtitle": "આધુનિક દરજી માટે સંપૂર્ણ સોફ્ટવેર સોલ્યુશન. ગ્રાહક વ્યવસ્થાપન, માપ, ઓર્ડર અને બિલિંગ — બધું એક જગ્યાએ.",
    "hero.available": "ગુજરાતી, हिंदी અને English માં ઉપલબ્ધ",
    "hero.startTrial": "મફત ટ્રાયલ શરૂ કરો",
    "hero.watchDemo": "ડેમો જુઓ",
    "hero.stat1Value": "૫,૦૦૦+",
    "hero.stat1Label": "દરજી અમારા પર ભરોસો કરે છે",
    "hero.stat2Value": "૨ મિનિટ",
    "hero.stat2Label": "દરેક ઓર્ડર માટે",
    "hero.stat3Value": "૧૦૦%",
    "hero.stat3Label": "ઓફલાઇન તૈયાર",
    "hero.worksOffline": "ઓફલાઇન કામ કરે છે",
    "hero.noInternet": "ઇન્ટરનેટની જરૂર નથી",
    
    // Features
    "features.badge": "ફીચર્સ",
    "features.title": "તમારા બિઝનેસને",
    "features.titleHighlight": " વધારવા માટે બધું",
    "features.subtitle": "નોટબુક અને રજિસ્ટરને ગુજરાતના દરજી માટે ખાસ ડિઝાઇન કરેલ શક્તિશાળી ડિજિટલ ટૂલ્સથી બદલો.",
    "features.customer": "ગ્રાહક વ્યવસ્થાપન",
    "features.customerDesc": "મોબાઇલ નંબરથી ગ્રાહકોને તરત શોધો. સંપૂર્ણ ઇતિહાસ તમારી આંગળીના ટેરવે.",
    "features.measurements": "સ્માર્ટ માપ",
    "features.measurementsDesc": "શર્ટ, પેન્ટ, કુર્તા, કોટી અને વધુ માટે પૂર્વ-નિર્મિત ટેમ્પલેટ. ફરી ક્યારેય માપ ગુમાવશો નહીં.",
    "features.orders": "ઓર્ડર ટ્રેકિંગ",
    "features.ordersDesc": "કટિંગથી ડિલિવરી સુધી દરેક ઓર્ડરને ટ્રેક કરો. એક નજરમાં જાણો શું પેન્ડિંગ છે.",
    "features.billing": "તાત્કાલિક બિલિંગ",
    "features.billingDesc": "સેકન્ડોમાં પ્રોફેશનલ બિલ બનાવો. પ્રિન્ટ કરો અથવા WhatsApp દ્વારા શેર કરો.",
    "features.offline": "ઓફલાઇન કામ કરે છે",
    "features.languages": "૩ ભાષાઓ",
    "features.whatsapp": "WhatsApp બિલ",
    "features.alerts": "ડિલિવરી એલર્ટ",
    "features.reports": "દૈનિક રિપોર્ટ",
    "features.payments": "ચુકવણી ટ્રેકિંગ",
    "features.mobile": "મોબાઇલ ફ્રેંડલી",
    "features.sync": "ઓટો સિંક",
    "features.more": "અને ઘણું બધું...",
    
    // Workflow
    "workflow.badge": "કેવી રીતે કામ કરે છે",
    "workflow.title": "પરંપરાગત vs.",
    "workflow.titleHighlight": " ડિજિટલ રીત",
    "workflow.subtitle": "જુઓ દરરોજ કેટલો સમય બચાવી શકો છો",
    "workflow.traditional": "પરંપરાગત પદ્ધતિ",
    "workflow.software": "StyleSavvy સાથે",
    "workflow.t1Step": "ગ્રાહક આવે છે",
    "workflow.t1Issue": "જૂની નોટબુક શોધો",
    "workflow.t2Step": "માપ શોધો",
    "workflow.t2Issue": "પાના ફેરવો",
    "workflow.t3Step": "નવો ઓર્ડર લખો",
    "workflow.t3Issue": "અનેક રજિસ્ટર",
    "workflow.t4Step": "બિલ ગણો",
    "workflow.t4Issue": "મેન્યુઅલ ગણતરી",
    "workflow.t5Step": "ડિલિવરી ટ્રેક કરો",
    "workflow.t5Issue": "બધા પાના તપાસો",
    "workflow.s1Step": "મોબાઇલ નંબર દાખલ કરો",
    "workflow.s1Benefit": "તાત્કાલિક શોધ",
    "workflow.s2Step": "બધા માપ જુઓ",
    "workflow.s2Benefit": "ઓટો-લોડ",
    "workflow.s3Step": "ઓર્ડર બનાવો",
    "workflow.s3Benefit": "એક સ્ક્રીન",
    "workflow.s4Step": "બિલ બનાવો",
    "workflow.s4Benefit": "ઓટો-ગણતરી",
    "workflow.s5Step": "સ્ટેટસ ટ્રેક કરો",
    "workflow.s5Benefit": "ડેશબોર્ડ વ્યૂ",
    "workflow.traditionalTime": "૧૬-૨૧ મિનિટ",
    "workflow.softwareTime": "૨ મિનિટથી ઓછી",
    "workflow.perCustomer": "દરેક ગ્રાહક દીઠ (સરેરાશ)",
    "workflow.saveUp": "બચાવો",
    "workflow.saveHours": "૩+ કલાક",
    "workflow.everyDay": "દરરોજ",
    "workflow.customers": "૨૦ ગ્રાહકો સાથે",
    
    // Pricing
    "pricing.badge": "કિંમત",
    "pricing.title": "સરળ, પારદર્શક",
    "pricing.titleHighlight": " કિંમત",
    "pricing.subtitle": "મફતમાં શરૂ કરો, જ્યારે વધુ જરૂર હોય ત્યારે અપગ્રેડ કરો. કોઈ છુપી ફી નથી.",
    "pricing.free": "મફત",
    "pricing.basic": "બેસિક",
    "pricing.professional": "પ્રોફેશનલ",
    "pricing.forever": "કાયમ માટે",
    "pricing.month": "/મહિનો",
    "pricing.freeDesc": "ખરીદતા પહેલા ટ્રાય કરવા માટે પરફેક્ટ",
    "pricing.basicDesc": "વધતી ટેલરિંગ દુકાનો માટે",
    "pricing.proDesc": "સ્થાપિત બિઝનેસ માટે",
    "pricing.getStarted": "શરૂ કરો",
    "pricing.startTrial": "મફત ટ્રાયલ શરૂ કરો",
    "pricing.mostPopular": "સૌથી લોકપ્રિય",
    "pricing.freeF1": "૫૦ ગ્રાહકો સુધી",
    "pricing.freeF2": "બેસિક માપ",
    "pricing.freeF3": "માત્ર લોકલ સ્ટોરેજ",
    "pricing.freeF4": "એક ડિવાઇસ",
    "pricing.basicF1": "અમર્યાદિત ગ્રાહકો",
    "pricing.basicF2": "બધા માપ ટેમ્પલેટ",
    "pricing.basicF3": "ક્લાઉડ બેકઅપ",
    "pricing.basicF4": "WhatsApp ઇન્ટિગ્રેશન",
    "pricing.basicF5": "૨ ડિવાઇસ",
    "pricing.basicF6": "ઇમેઇલ સપોર્ટ",
    "pricing.proF1": "બેસિકમાં બધું",
    "pricing.proF2": "અનેક કારીગર",
    "pricing.proF3": "SMS નોટિફિકેશન",
    "pricing.proF4": "એડવાન્સ રિપોર્ટ",
    "pricing.proF5": "૫ ડિવાઇસ",
    "pricing.proF6": "પ્રાયોરિટી સપોર્ટ",
    "pricing.proF7": "કારીગર વેજ ટ્રેકિંગ",
    "pricing.oneTime": "એક વખતની ચુકવણી પસંદ છે?",
    "pricing.lifetime": "માત્ર આટલામાં લાઇફટાઇમ એક્સેસ મેળવો",
    "pricing.lifetimePrice": "₹૯,૯૯૯",
    "pricing.noMonthly": "(કોઈ માસિક ફી નથી!)",
    "pricing.learnMore": "લાઇફટાઇમ ડીલ વિશે વધુ જાણો",
    
    // Languages Section
    "lang.badge": "બહુ-ભાષા સપોર્ટ",
    "lang.title": "તમારી પોતાની",
    "lang.titleHighlight": "ભાષામાં વાપરો",
    "lang.subtitle": "અમે સમજીએ છીએ કે તમારી માતૃભાષામાં સોફ્ટવેર વાપરવાથી આરામ મળે છે. એટલે StyleSavvy ગુજરાતી, હિન્દી અને અંગ્રેજીમાં સંપૂર્ણ ઉપલબ્ધ છે.",
    "lang.feature1": "બધી ૩ ભાષાઓમાં સંપૂર્ણ UI",
    "lang.feature2": "માપના લેબલ અનુવાદિત",
    "lang.feature3": "મદદ અને ટ્યુટોરિયલ ઉપલબ્ધ",
    "lang.feature4": "ગુજરાતીમાં ગ્રાહક સપોર્ટ",
    "lang.primary": "પ્રાથમિક",
    "lang.gujarati": "ગુજરાતી",
    "lang.hindi": "હિન્દી",
    "lang.english": "અંગ્રેજી",
    "lang.sampleGu": "તમારા ગ્રાહકોની માપ અને ઓર્ડર સરળતાથી મેનેજ કરો",
    "lang.sampleHi": "अपने ग्राहकों की नाप और ऑर्डर आसानी से प्रबंधित करें",
    "lang.sampleEn": "Easily manage your customers' measurements and orders",
    
    // CTA
    "cta.title": "તમારા ટેલરિંગ બિઝનેસને",
    "cta.titleHighlight": "ટ્રાન્સફોર્મ કરવા તૈયાર છો?",
    "cta.subtitle": "સુરતના હજારો દરજીઓ સાથે જોડાઓ જેમણે પહેલેથી સ્વિચ કર્યું છે. આજે જ તમારી મફત ટ્રાયલ શરૂ કરો — કોઈ ક્રેડિટ કાર્ડ જરૂરી નથી.",
    "cta.trial": "૧૪-દિવસની મફત ટ્રાયલ શરૂ કરો",
    "cta.contact": "સેલ્સનો સંપર્ક કરો",
    "cta.whatsapp": "WhatsApp સપોર્ટ ઉપલબ્ધ",
    
    // Footer
    "footer.tagline": "ગુજરાત અને તેની બહારના આધુનિક ટેલરિંગ બિઝનેસ માટે બનાવેલ સંપૂર્ણ દરજી મેનેજમેન્ટ સોફ્ટવેર.",
    "footer.taglineGu": "ગુજરાતના દરજીઓ માટે સંપૂર્ણ સોફ્ટવેર",
    "footer.product": "પ્રોડક્ટ",
    "footer.support": "સપોર્ટ",
    "footer.company": "કંપની",
    "footer.features": "ફીચર્સ",
    "footer.pricing": "કિંમત",
    "footer.howItWorks": "કેવી રીતે કામ કરે છે",
    "footer.downloadApp": "એપ ડાઉનલોડ કરો",
    "footer.helpCenter": "હેલ્પ સેન્ટર",
    "footer.videoTutorials": "વિડિયો ટ્યુટોરિયલ",
    "footer.contactUs": "અમારો સંપર્ક કરો",
    "footer.whatsappSupport": "WhatsApp સપોર્ટ",
    "footer.aboutUs": "અમારા વિશે",
    "footer.careers": "કરિયર",
    "footer.privacy": "પ્રાઇવસી પોલિસી",
    "footer.terms": "સેવાની શરતો",
    "footer.rights": "© ૨૦૨૪ StyleSavvy. બધા અધિકારો સુરક્ષિત.",
    "footer.madeWith": "સુરતના ટેલરિંગ સમુદાય માટે ❤️ થી બનાવેલ",
  },
  hi: {
    // Navbar
    "nav.features": "फीचर्स",
    "nav.howItWorks": "कैसे काम करता है",
    "nav.pricing": "कीमत",
    "nav.languages": "भाषाएं",
    "nav.login": "लॉग इन",
    "nav.startTrial": "मुफ्त ट्रायल शुरू करें",
    
    // Dashboard Nav
    "nav.dashboard": "डैशबोर्ड",
    "nav.customers": "ग्राहक",
    "nav.orders": "ऑर्डर",
    "nav.online": "ऑनलाइन",
    "nav.offline": "ऑफलाइन",
    
    // Dashboard
    "dashboard.welcome": "स्वागत है",
    "dashboard.subtitle": "ग्राहक लुकअप, माप और ऑर्डर प्रबंधन के साथ अपने टेलरिंग बिज़नेस को सुव्यवस्थित करें।",
    "dashboard.searchPlaceholder": "त्वरित खोज: मोबाइल नंबर या ग्राहक का नाम दर्ज करें...",
    "dashboard.customers": "ग्राहक",
    "dashboard.measurements": "माप",
    "dashboard.orders": "ऑर्डर",
    "dashboard.revenue": "आय",
    "dashboard.newCustomer": "नया ग्राहक",
    "dashboard.allCustomers": "सभी ग्राहक",
    "dashboard.allOrders": "सभी ऑर्डर",
    "dashboard.pendingOrders": "पेंडिंग ऑर्डर",
    "dashboard.readyForPickup": "पिकअप के लिए तैयार",
    "dashboard.outstandingBalance": "बकाया राशि",
    "dashboard.upcomingDeliveries": "आगामी डिलीवरी",
    "dashboard.recentOrders": "हाल के ऑर्डर",
    "dashboard.viewAll": "सभी देखें",
    "dashboard.noPendingOrders": "कोई पेंडिंग ऑर्डर नहीं",
    "dashboard.noOrders": "अभी तक कोई ऑर्डर नहीं। अपना पहला ऑर्डर बनाएं!",
    
    // Customers Page
    "customers.title": "ग्राहक",
    "customers.totalCustomers": "कुल ग्राहक",
    "customers.addCustomer": "ग्राहक जोड़ें",
    "customers.filterPlaceholder": "नाम, मोबाइल या टैग से फ़िल्टर करें...",
    "customers.name": "नाम",
    "customers.date": "तारीख",
    "customers.noCustomersFound": "कोई ग्राहक नहीं मिला",
    "customers.adjustSearch": "अपने खोज मानदंड को समायोजित करने का प्रयास करें",
    "customers.addFirst": "अपना पहला ग्राहक जोड़कर शुरू करें",
    
    // Customer Detail
    "customerDetail.notFound": "ग्राहक नहीं मिला",
    "customerDetail.notFoundDesc": "जिस ग्राहक को आप ढूंढ रहे हैं वह मौजूद नहीं है।",
    "customerDetail.goToCustomers": "ग्राहकों पर जाएं",
    "customerDetail.back": "ग्राहकों पर वापस",
    "customerDetail.edit": "संपादित करें",
    "customerDetail.delete": "हटाएं",
    "customerDetail.deleteTitle": "ग्राहक हटाएं?",
    "customerDetail.deleteDesc": "यह {name} और उनके सभी माप और ऑर्डर को स्थायी रूप से हटा देगा। यह क्रिया पूर्ववत नहीं की जा सकती।",
    "customerDetail.cancel": "रद्द करें",
    "customerDetail.customerSince": "ग्राहक तब से",
    "customerDetail.measurements": "माप",
    "customerDetail.orders": "ऑर्डर",
    "customerDetail.totalValue": "कुल मूल्य",
    "customerDetail.addMeasurement": "माप जोड़ें",
    "customerDetail.noMeasurementsYet": "अभी तक कोई माप नहीं",
    "customerDetail.addFirstMeasurement": "इस ग्राहक के लिए पहला माप जोड़ें",
    "customerDetail.createOrder": "ऑर्डर बनाएं",
    "customerDetail.noOrdersYet": "अभी तक कोई ऑर्डर नहीं",
    "customerDetail.createFirstOrder": "इस ग्राहक के लिए पहला ऑर्डर बनाएं",
    
    // Customer Form
    "customerForm.back": "वापस",
    "customerForm.newCustomer": "नया ग्राहक",
    "customerForm.editCustomer": "ग्राहक संपादित करें",
    "customerForm.name": "नाम",
    "customerForm.nameRequired": "नाम *",
    "customerForm.enterName": "ग्राहक का नाम दर्ज करें",
    "customerForm.mobile": "मोबाइल नंबर",
    "customerForm.mobileRequired": "मोबाइल नंबर *",
    "customerForm.enterMobile": "10-अंकों का मोबाइल दर्ज करें",
    "customerForm.duplicateWarning": "इस नंबर के साथ ग्राहक \"{name}\" पहले से मौजूद है",
    "customerForm.email": "ईमेल",
    "customerForm.enterEmail": "ईमेल पता दर्ज करें",
    "customerForm.customerType": "ग्राहक प्रकार",
    "customerForm.vip": "VIP",
    "customerForm.regular": "रेगुलर",
    "customerForm.walkin": "वॉक-इन",
    "customerForm.address": "पता",
    "customerForm.enterAddress": "पूरा पता दर्ज करें",
    "customerForm.notes": "नोट्स",
    "customerForm.enterNotes": "कोई विशेष निर्देश या प्राथमिकताएं",
    "customerForm.cancel": "रद्द करें",
    "customerForm.save": "ग्राहक सहेजें",
    "customerForm.update": "ग्राहक अपडेट करें",
    "customerForm.nameError": "कृपया ग्राहक का नाम दर्ज करें",
    "customerForm.mobileError": "कृपया एक वैध मोबाइल नंबर दर्ज करें",
    "customerForm.duplicateError": "इस मोबाइल नंबर के साथ ग्राहक पहले से मौजूद है",
    "customerForm.addedSuccess": "ग्राहक सफलतापूर्वक जोड़ा गया",
    "customerForm.updatedSuccess": "ग्राहक सफलतापूर्वक अपडेट किया गया",
    
    // Customer Search
    "customerSearch.placeholder": "मोबाइल नंबर या नाम से खोजें...",
    "customerSearch.noCustomersFound": "कोई ग्राहक नहीं मिला",
    "customerSearch.addNewCustomer": "नया ग्राहक जोड़ें",
    
    // Orders Page
    "orders.title": "ऑर्डर",
    "orders.totalOrders": "कुल ऑर्डर",
    "orders.all": "सभी",
    "orders.pending": "पेंडिंग",
    "orders.cutting": "कटिंग",
    "orders.stitching": "सिलाई",
    "orders.trial": "ट्रायल",
    "orders.ready": "तैयार",
    "orders.delivered": "डिलीवर",
    "orders.cancelled": "रद्द",
    "orders.searchPlaceholder": "ऑर्डर नंबर या ग्राहक द्वारा खोजें...",
    "orders.allPayments": "सभी भुगतान",
    "orders.unpaid": "अवैतनिक",
    "orders.partial": "आंशिक",
    "orders.paid": "भुगतान",
    "orders.noOrdersFound": "कोई ऑर्डर नहीं मिला",
    "orders.adjustFilters": "अपने फ़िल्टर समायोजित करने का प्रयास करें",
    "orders.createFromCustomers": "ग्राहक प्रोफ़ाइल से ऑर्डर बनाएं",
    "orders.goToCustomers": "ग्राहकों पर जाएं",
    
    // Order Detail
    "orderDetail.notFound": "ऑर्डर नहीं मिला",
    "orderDetail.notFoundDesc": "जिस ऑर्डर को आप ढूंढ रहे हैं वह मौजूद नहीं है।",
    "orderDetail.goToOrders": "ऑर्डर पर जाएं",
    "orderDetail.back": "ऑर्डर पर वापस",
    "orderDetail.order": "ऑर्डर",
    "orderDetail.createdOn": "बनाया गया",
    "orderDetail.edit": "संपादित करें",
    "orderDetail.cancel": "रद्द करें",
    "orderDetail.printInvoice": "इनवॉइस प्रिंट करें",
    "orderDetail.customerDetails": "ग्राहक विवरण",
    "orderDetail.viewProfile": "प्रोफ़ाइल देखें",
    "orderDetail.orderItems": "ऑर्डर आइटम",
    "orderDetail.total": "कुल",
    "orderDetail.orderStatus": "ऑर्डर स्थिति",
    "orderDetail.status": "स्थिति",
    "orderDetail.deliveryDate": "डिलीवरी तारीख",
    "orderDetail.urgency": "अर्जेंसी",
    "orderDetail.normal": "सामान्य",
    "orderDetail.urgent": "अर्जेंट",
    "orderDetail.express": "एक्सप्रेस",
    "orderDetail.paidAmount": "भुगतान राशि",
    "orderDetail.saveChanges": "बदलाव सहेजें",
    "orderDetail.payment": "भुगतान",
    "orderDetail.balance": "बकाया",
    "orderDetail.fullyPaid": "पूर्ण भुगतान",
    "orderDetail.partiallyPaid": "आंशिक भुगतान",
    "orderDetail.orderUpdated": "ऑर्डर अपडेट किया गया",
    "orderDetail.shareWhatsApp": "WhatsApp पर शेयर करें",
    "orderDetail.whatsappOpened": "WhatsApp खोल रहे हैं...",
    
    // Order Form
    "orderForm.newOrder": "नया ऑर्डर",
    "orderForm.editOrder": "ऑर्डर संपादित करें",
    "orderForm.orderItems": "ऑर्डर आइटम",
    "orderForm.addItem": "आइटम जोड़ें",
    "orderForm.garmentType": "कपड़े का प्रकार",
    "orderForm.shirt": "शर्ट",
    "orderForm.pant": "पैंट",
    "orderForm.kurta": "कुर्ता",
    "orderForm.koti": "कोटी",
    "orderForm.waistcoat": "वेस्टकोट",
    "orderForm.qty": "मात्रा",
    "orderForm.price": "कीमत",
    "orderForm.urgencyLevel": "अर्जेंसी लेवल",
    "orderForm.normal7days": "सामान्य (7 दिन)",
    "orderForm.urgent3days": "अर्जेंट (3 दिन) +25%",
    "orderForm.express1day": "एक्सप्रेस (1 दिन) +50%",
    "orderForm.deliveryDate": "डिलीवरी तारीख",
    "orderForm.totalAmount": "कुल राशि",
    "orderForm.advancePayment": "अग्रिम भुगतान",
    "orderForm.orderNotes": "ऑर्डर नोट्स",
    "orderForm.notesPlaceholder": "इस ऑर्डर के लिए कोई विशेष निर्देश...",
    "orderForm.cancel": "रद्द करें",
    "orderForm.createOrder": "ऑर्डर बनाएं",
    "orderForm.updateOrder": "ऑर्डर अपडेट करें",
    "orderForm.itemError": "कृपया कम से कम एक आइटम जोड़ें",
    "orderForm.createdSuccess": "ऑर्डर #{number} बनाया गया",
    "orderForm.updatedSuccess": "ऑर्डर सफलतापूर्वक अपडेट किया गया",
    "orderForm.measurements": "माप",
    
    // Order Card
    "orderCard.delivery": "डिलीवरी",
    "orderCard.balance": "बकाया",
    "orderCard.view": "देखें",
    "orderCard.edit": "संपादित करें",
    
    // Measurement Form
    "measurementForm.newMeasurement": "नया माप",
    "measurementForm.editMeasurement": "माप संपादित करें",
    "measurementForm.copyPrevious": "पिछला कॉपी करें",
    "measurementForm.shirt": "शर्ट",
    "measurementForm.pant": "पैंट",
    "measurementForm.kurta": "कुर्ता",
    "measurementForm.koti": "कोटी",
    "measurementForm.waistcoat": "वेस्टकोट",
    "measurementForm.length": "लंबाई",
    "measurementForm.chest": "छाती",
    "measurementForm.waist": "कमर",
    "measurementForm.shoulder": "कंधा",
    "measurementForm.sleeveLength": "स्लीव लंबाई",
    "measurementForm.sleeveOpening": "स्लीव ओपनिंग",
    "measurementForm.collar": "कॉलर",
    "measurementForm.armHole": "आर्म होल",
    "measurementForm.cuffSize": "कफ साइज़",
    "measurementForm.frontChest": "फ्रंट छाती",
    "measurementForm.backWidth": "पीछे की चौड़ाई",
    "measurementForm.hip": "हिप",
    "measurementForm.thigh": "थाई",
    "measurementForm.knee": "घुटना",
    "measurementForm.bottom": "बॉटम",
    "measurementForm.crotch": "क्रॉच",
    "measurementForm.rise": "राइज़",
    "measurementForm.inseam": "इनसीम",
    "measurementForm.slit": "स्लिट",
    "measurementForm.daaman": "दामन",
    "measurementForm.frontOpening": "फ्रंट ओपनिंग",
    "measurementForm.frontLength": "फ्रंट लंबाई",
    "measurementForm.backLength": "पीछे की लंबाई",
    "measurementForm.notes": "नोट्स / विशेष निर्देश",
    "measurementForm.notesPlaceholder": "कोई विशेष टेलरिंग निर्देश या नोट्स जोड़ें...",
    "measurementForm.cancel": "रद्द करें",
    "measurementForm.save": "माप सहेजें",
    "measurementForm.copiedSuccess": "पिछले माप से कॉपी किया गया",
    "measurementForm.noPrevious": "इस प्रकार के लिए कोई पिछला माप नहीं मिला",
    "measurementForm.savedSuccess": "माप सहेजा गया",
    "measurementForm.updatedSuccess": "माप अपडेट किया गया",
    
    // Measurement Card
    "measurementCard.edit": "संपादित करें",
    "measurementCard.delete": "हटाएं",
    "measurementCard.deletedSuccess": "माप हटाया गया",
    
    // Common
    "common.save": "सहेजें",
    "common.cancel": "रद्द करें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.view": "देखें",
    "common.back": "वापस",
    "common.search": "खोजें",
    "common.filter": "फ़िल्टर",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफल",
    "common.customerDeleted": "ग्राहक हटाया गया",
    
    // Hero
    "hero.badge": "सूरत के टेलरिंग उद्योग के लिए बनाया गया",
    "hero.title1": "अपने",
    "hero.title2": "टेलरिंग बिज़नेस को",
    "hero.title3": "पहले जैसा कभी नहीं मैनेज करें",
    "hero.subtitle": "आधुनिक दर्जी के लिए पूर्ण सॉफ्टवेयर समाधान। ग्राहक प्रबंधन, माप, ऑर्डर और बिलिंग — सब एक जगह।",
    "hero.available": "ગુજરાતી, हिंदी और English में उपलब्ध",
    "hero.startTrial": "मुफ्त ट्रायल शुरू करें",
    "hero.watchDemo": "डेमो देखें",
    "hero.stat1Value": "5,000+",
    "hero.stat1Label": "दर्जी हम पर भरोसा करते हैं",
    "hero.stat2Value": "2 मिनट",
    "hero.stat2Label": "प्रति ऑर्डर",
    "hero.stat3Value": "100%",
    "hero.stat3Label": "ऑफलाइन रेडी",
    "hero.worksOffline": "ऑफलाइन काम करता है",
    "hero.noInternet": "इंटरनेट की जरूरत नहीं",
    
    // Features
    "features.badge": "फीचर्स",
    "features.title": "आपके बिज़नेस को",
    "features.titleHighlight": " बढ़ाने के लिए सब कुछ",
    "features.subtitle": "नोटबुक और रजिस्टरों को गुजरात के दर्जियों के लिए विशेष रूप से डिज़ाइन किए गए शक्तिशाली डिजिटल टूल्स से बदलें।",
    "features.customer": "ग्राहक प्रबंधन",
    "features.customerDesc": "मोबाइल नंबर से ग्राहकों को तुरंत खोजें। पूरा इतिहास आपकी उंगलियों पर।",
    "features.measurements": "स्मार्ट माप",
    "features.measurementsDesc": "शर्ट, पैंट, कुर्ता, कोटी और अधिक के लिए पूर्व-निर्मित टेम्पलेट। फिर कभी माप न खोएं।",
    "features.orders": "ऑर्डर ट्रैकिंग",
    "features.ordersDesc": "कटिंग से डिलीवरी तक हर ऑर्डर को ट्रैक करें। एक नज़र में जानें क्या पेंडिंग है।",
    "features.billing": "तत्काल बिलिंग",
    "features.billingDesc": "सेकंडों में प्रोफेशनल बिल बनाएं। प्रिंट करें या WhatsApp से शेयर करें।",
    "features.offline": "ऑफलाइन काम करता है",
    "features.languages": "3 भाषाएं",
    "features.whatsapp": "WhatsApp बिल",
    "features.alerts": "डिलीवरी अलर्ट",
    "features.reports": "दैनिक रिपोर्ट",
    "features.payments": "भुगतान ट्रैकिंग",
    "features.mobile": "मोबाइल फ्रेंडली",
    "features.sync": "ऑटो सिंक",
    "features.more": "और भी बहुत कुछ...",
    
    // Workflow
    "workflow.badge": "कैसे काम करता है",
    "workflow.title": "पारंपरिक vs.",
    "workflow.titleHighlight": " डिजिटल तरीका",
    "workflow.subtitle": "देखें हर दिन कितना समय बचा सकते हैं",
    "workflow.traditional": "पारंपरिक तरीका",
    "workflow.software": "StyleSavvy के साथ",
    "workflow.t1Step": "ग्राहक आता है",
    "workflow.t1Issue": "पुरानी नोटबुक खोजो",
    "workflow.t2Step": "माप खोजो",
    "workflow.t2Issue": "पेज पलटो",
    "workflow.t3Step": "नया ऑर्डर लिखो",
    "workflow.t3Issue": "कई रजिस्टर",
    "workflow.t4Step": "बिल की गणना करो",
    "workflow.t4Issue": "मैन्युअल गणना",
    "workflow.t5Step": "डिलीवरी ट्रैक करो",
    "workflow.t5Issue": "सभी पेज जांचो",
    "workflow.s1Step": "मोबाइल नंबर दर्ज करें",
    "workflow.s1Benefit": "तत्काल खोज",
    "workflow.s2Step": "सभी माप देखें",
    "workflow.s2Benefit": "ऑटो-लोड",
    "workflow.s3Step": "ऑर्डर बनाएं",
    "workflow.s3Benefit": "एक स्क्रीन",
    "workflow.s4Step": "बिल बनाएं",
    "workflow.s4Benefit": "ऑटो-गणना",
    "workflow.s5Step": "स्टेटस ट्रैक करें",
    "workflow.s5Benefit": "डैशबोर्ड व्यू",
    "workflow.traditionalTime": "16-21 मिनट",
    "workflow.softwareTime": "2 मिनट से कम",
    "workflow.perCustomer": "प्रति ग्राहक (औसत)",
    "workflow.saveUp": "बचाएं",
    "workflow.saveHours": "3+ घंटे",
    "workflow.everyDay": "हर दिन",
    "workflow.customers": "20 ग्राहकों के साथ",
    
    // Pricing
    "pricing.badge": "कीमत",
    "pricing.title": "सरल, पारदर्शी",
    "pricing.titleHighlight": " कीमत",
    "pricing.subtitle": "मुफ्त में शुरू करें, जब ज़्यादा चाहिए तब अपग्रेड करें। कोई छुपी फीस नहीं।",
    "pricing.free": "मुफ्त",
    "pricing.basic": "बेसिक",
    "pricing.professional": "प्रोफेशनल",
    "pricing.forever": "हमेशा के लिए",
    "pricing.month": "/महीना",
    "pricing.freeDesc": "खरीदने से पहले ट्राई करने के लिए परफेक्ट",
    "pricing.basicDesc": "बढ़ती टेलरिंग दुकानों के लिए",
    "pricing.proDesc": "स्थापित बिज़नेस के लिए",
    "pricing.getStarted": "शुरू करें",
    "pricing.startTrial": "मुफ्त ट्रायल शुरू करें",
    "pricing.mostPopular": "सबसे लोकप्रिय",
    "pricing.freeF1": "50 ग्राहकों तक",
    "pricing.freeF2": "बेसिक माप",
    "pricing.freeF3": "सिर्फ लोकल स्टोरेज",
    "pricing.freeF4": "एक डिवाइस",
    "pricing.basicF1": "असीमित ग्राहक",
    "pricing.basicF2": "सभी माप टेम्पलेट",
    "pricing.basicF3": "क्लाउड बैकअप",
    "pricing.basicF4": "WhatsApp इंटीग्रेशन",
    "pricing.basicF5": "2 डिवाइस",
    "pricing.basicF6": "ईमेल सपोर्ट",
    "pricing.proF1": "बेसिक में सब कुछ",
    "pricing.proF2": "कई कारीगर",
    "pricing.proF3": "SMS नोटिफिकेशन",
    "pricing.proF4": "एडवांस रिपोर्ट",
    "pricing.proF5": "5 डिवाइस",
    "pricing.proF6": "प्राथमिकता सपोर्ट",
    "pricing.proF7": "कारीगर वेज ट्रैकिंग",
    "pricing.oneTime": "एक बार का भुगतान पसंद है?",
    "pricing.lifetime": "सिर्फ इतने में लाइफटाइम एक्सेस पाएं",
    "pricing.lifetimePrice": "₹9,999",
    "pricing.noMonthly": "(कोई मासिक फीस नहीं!)",
    "pricing.learnMore": "लाइफटाइम डील के बारे में और जानें",
    
    // Languages Section
    "lang.badge": "बहु-भाषा सपोर्ट",
    "lang.title": "अपनी खुद की",
    "lang.titleHighlight": "भाषा में इस्तेमाल करें",
    "lang.subtitle": "हम समझते हैं कि अपनी मातृभाषा में सॉफ्टवेयर का उपयोग करने से आराम मिलता है। इसलिए StyleSavvy गुजराती, हिंदी और अंग्रेजी में पूरी तरह उपलब्ध है।",
    "lang.feature1": "सभी 3 भाषाओं में पूर्ण UI",
    "lang.feature2": "माप लेबल अनुवादित",
    "lang.feature3": "मदद और ट्यूटोरियल उपलब्ध",
    "lang.feature4": "गुजराती में ग्राहक सपोर्ट",
    "lang.primary": "प्राथमिक",
    "lang.gujarati": "गुजराती",
    "lang.hindi": "हिंदी",
    "lang.english": "अंग्रेजी",
    "lang.sampleGu": "તમારા ગ્રાહકોની માપ અને ઓર્ડર સરળતાથી મેનેજ કરો",
    "lang.sampleHi": "अपने ग्राहकों की नाप और ऑर्डर आसानी से प्रबंधित करें",
    "lang.sampleEn": "Easily manage your customers' measurements and orders",
    
    // CTA
    "cta.title": "अपने टेलरिंग बिज़नेस को",
    "cta.titleHighlight": "ट्रांसफॉर्म करने के लिए तैयार हैं?",
    "cta.subtitle": "सूरत के हजारों दर्जियों से जुड़ें जिन्होंने पहले ही स्विच किया है। आज ही अपना मुफ्त ट्रायल शुरू करें — कोई क्रेडिट कार्ड जरूरी नहीं।",
    "cta.trial": "14-दिन का मुफ्त ट्रायल शुरू करें",
    "cta.contact": "सेल्स से संपर्क करें",
    "cta.whatsapp": "WhatsApp सपोर्ट उपलब्ध",
    
    // Footer
    "footer.tagline": "गुजरात और उससे परे आधुनिक टेलरिंग बिज़नेस के लिए बनाया गया पूर्ण दर्जी प्रबंधन सॉफ्टवेयर।",
    "footer.taglineGu": "गुजरात के दर्जियों के लिए पूर्ण सॉफ्टवेयर",
    "footer.product": "प्रोडक्ट",
    "footer.support": "सपोर्ट",
    "footer.company": "कंपनी",
    "footer.features": "फीचर्स",
    "footer.pricing": "कीमत",
    "footer.howItWorks": "कैसे काम करता है",
    "footer.downloadApp": "ऐप डाउनलोड करें",
    "footer.helpCenter": "हेल्प सेंटर",
    "footer.videoTutorials": "वीडियो ट्यूटोरियल",
    "footer.contactUs": "हमसे संपर्क करें",
    "footer.whatsappSupport": "WhatsApp सपोर्ट",
    "footer.aboutUs": "हमारे बारे में",
    "footer.careers": "करियर",
    "footer.privacy": "प्राइवेसी पॉलिसी",
    "footer.terms": "सेवा की शर्तें",
    "footer.rights": "© 2024 StyleSavvy. सर्वाधिकार सुरक्षित।",
    "footer.madeWith": "सूरत की टेलरिंग समुदाय के लिए ❤️ से बनाया गया",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
