import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "gu" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Navbar
    "nav.features": "Features",
    "nav.howItWorks": "How It Works",
    "nav.pricing": "Pricing",
    "nav.languages": "Languages",
    "nav.login": "Log In",
    "nav.startTrial": "Start Free Trial",
    
    // Hero
    "hero.badge": "Built for Surat's Tailoring Industry",
    "hero.title1": "Manage Your",
    "hero.title2": "Tailoring Business",
    "hero.title3": "Like Never Before",
    "hero.subtitle": "The complete software solution for modern tailors. Customer management, measurements, orders, and billing — all in one place.",
    "hero.available": "Available in ગુજરાતી, हिंदी & English",
    "hero.startTrial": "Start Free Trial",
    "hero.watchDemo": "Watch Demo",
    "hero.stat1Value": "5,000+",
    "hero.stat1Label": "Tailors Trust Us",
    "hero.stat2Value": "2 Min",
    "hero.stat2Label": "Per Order",
    "hero.stat3Value": "100%",
    "hero.stat3Label": "Offline Ready",
    "hero.worksOffline": "Works Offline",
    "hero.noInternet": "No internet needed",
    
    // Features
    "features.badge": "Features",
    "features.title": "Everything You Need to",
    "features.titleHighlight": " Grow Your Business",
    "features.subtitle": "Replace notebooks and registers with powerful digital tools designed specifically for tailors in Gujarat.",
    "features.customer": "Customer Management",
    "features.customerDesc": "Search customers instantly by mobile number. Complete history at your fingertips.",
    "features.measurements": "Smart Measurements",
    "features.measurementsDesc": "Pre-built templates for Shirt, Pant, Kurta, Koti & more. Never lose measurements again.",
    "features.orders": "Order Tracking",
    "features.ordersDesc": "Track every order from cutting to delivery. Know what's pending at a glance.",
    "features.billing": "Instant Billing",
    "features.billingDesc": "Generate professional bills in seconds. Print or share via WhatsApp.",
    "features.offline": "Works Offline",
    "features.languages": "3 Languages",
    "features.whatsapp": "WhatsApp Bills",
    "features.alerts": "Delivery Alerts",
    "features.reports": "Daily Reports",
    "features.payments": "Payment Tracking",
    "features.mobile": "Mobile Friendly",
    "features.sync": "Auto Sync",
    "features.more": "And Much More...",
    
    // Workflow
    "workflow.badge": "How It Works",
    "workflow.title": "Traditional vs.",
    "workflow.titleHighlight": " Digital Way",
    "workflow.subtitle": "See how much time you can save every single day",
    "workflow.traditional": "Traditional Method",
    "workflow.software": "With StyleSavvy",
    "workflow.t1Step": "Customer comes",
    "workflow.t1Issue": "Find old notebook",
    "workflow.t2Step": "Search measurements",
    "workflow.t2Issue": "Flip through pages",
    "workflow.t3Step": "Write new order",
    "workflow.t3Issue": "Multiple registers",
    "workflow.t4Step": "Calculate bill",
    "workflow.t4Issue": "Manual calculation",
    "workflow.t5Step": "Track delivery",
    "workflow.t5Issue": "Check all pages",
    "workflow.s1Step": "Enter mobile number",
    "workflow.s1Benefit": "Instant search",
    "workflow.s2Step": "View all measurements",
    "workflow.s2Benefit": "Auto-loads",
    "workflow.s3Step": "Create order",
    "workflow.s3Benefit": "One screen",
    "workflow.s4Step": "Generate bill",
    "workflow.s4Benefit": "Auto-calculated",
    "workflow.s5Step": "Track status",
    "workflow.s5Benefit": "Dashboard view",
    "workflow.traditionalTime": "16-21 min",
    "workflow.softwareTime": "Under 2 min",
    "workflow.perCustomer": "per customer (average)",
    "workflow.saveUp": "Save up to",
    "workflow.saveHours": "3+ Hours",
    "workflow.everyDay": "Every day with",
    "workflow.customers": "20 Customers",
    
    // Pricing
    "pricing.badge": "Pricing",
    "pricing.title": "Simple, Transparent",
    "pricing.titleHighlight": " Pricing",
    "pricing.subtitle": "Start free, upgrade when you need more. No hidden charges.",
    "pricing.free": "Free",
    "pricing.basic": "Basic",
    "pricing.professional": "Professional",
    "pricing.forever": "forever",
    "pricing.month": "/month",
    "pricing.freeDesc": "Perfect to try before you buy",
    "pricing.basicDesc": "For growing tailoring shops",
    "pricing.proDesc": "For established businesses",
    "pricing.getStarted": "Get Started",
    "pricing.startTrial": "Start Free Trial",
    "pricing.mostPopular": "Most Popular",
    "pricing.freeF1": "Up to 50 customers",
    "pricing.freeF2": "Basic measurements",
    "pricing.freeF3": "Local storage only",
    "pricing.freeF4": "Single device",
    "pricing.basicF1": "Unlimited customers",
    "pricing.basicF2": "All measurement templates",
    "pricing.basicF3": "Cloud backup",
    "pricing.basicF4": "WhatsApp integration",
    "pricing.basicF5": "2 devices",
    "pricing.basicF6": "Email support",
    "pricing.proF1": "Everything in Basic",
    "pricing.proF2": "Multiple workers",
    "pricing.proF3": "SMS notifications",
    "pricing.proF4": "Advanced reports",
    "pricing.proF5": "5 devices",
    "pricing.proF6": "Priority support",
    "pricing.proF7": "Worker wage tracking",
    "pricing.oneTime": "Prefer One-Time Payment?",
    "pricing.lifetime": "Get lifetime access for just",
    "pricing.lifetimePrice": "₹9,999",
    "pricing.noMonthly": "(no monthly fees!)",
    "pricing.learnMore": "Learn More About Lifetime Deal",
    
    // Languages Section
    "lang.badge": "Multi-Language Support",
    "lang.title": "Use in Your Own",
    "lang.titleHighlight": "Language",
    "lang.subtitle": "We understand that comfort comes from using software in your mother tongue. That's why StyleSavvy is fully available in Gujarati, Hindi, and English.",
    "lang.feature1": "Complete UI in all 3 languages",
    "lang.feature2": "Measurement labels translated",
    "lang.feature3": "Help & tutorials available",
    "lang.feature4": "Customer support in Gujarati",
    "lang.primary": "Primary",
    "lang.gujarati": "Gujarati",
    "lang.hindi": "Hindi",
    "lang.english": "English",
    "lang.sampleGu": "Easily manage your customers' measurements and orders",
    "lang.sampleHi": "Easily manage your customers' measurements and orders",
    "lang.sampleEn": "Easily manage your customers' measurements and orders",
    
    // CTA
    "cta.title": "Ready to Transform Your",
    "cta.titleHighlight": "Tailoring Business?",
    "cta.subtitle": "Join thousands of tailors in Surat who have already made the switch. Start your free trial today — no credit card required.",
    "cta.trial": "Start 14-Day Free Trial",
    "cta.contact": "Contact Sales",
    "cta.whatsapp": "WhatsApp Support Available",
    
    // Footer
    "footer.tagline": "The complete tailor management software built for modern tailoring businesses in Gujarat and beyond.",
    "footer.taglineGu": "Complete software for Gujarat's tailors",
    "footer.product": "Product",
    "footer.support": "Support",
    "footer.company": "Company",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.howItWorks": "How It Works",
    "footer.downloadApp": "Download App",
    "footer.helpCenter": "Help Center",
    "footer.videoTutorials": "Video Tutorials",
    "footer.contactUs": "Contact Us",
    "footer.whatsappSupport": "WhatsApp Support",
    "footer.aboutUs": "About Us",
    "footer.careers": "Careers",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.rights": "© 2024 StyleSavvy. All rights reserved.",
    "footer.madeWith": "Made with ❤️ for Surat's Tailoring Community",
  },
  gu: {
    // Navbar
    "nav.features": "ફીચર્સ",
    "nav.howItWorks": "કેવી રીતે કામ કરે છે",
    "nav.pricing": "કિંમત",
    "nav.languages": "ભાષાઓ",
    "nav.login": "લૉગ ઇન",
    "nav.startTrial": "મફત ટ્રાયલ શરૂ કરો",
    
    // Hero
    "hero.badge": "સુરતના ટેલરિંગ ઉદ્યોગ માટે બનાવેલ",
    "hero.title1": "તમારો",
    "hero.title2": "ટેલરિંગ બિઝનેસ",
    "hero.title3": "પહેલા ક્યારેય ન હતો એમ મેનેજ કરો",
    "hero.subtitle": "આધુનિક દરજી માટે સંપૂર્ણ સોફ્ટવેર સોલ્યુશન. ગ્રાહક વ્યવસ્થાપન, માપ, ઓર્ડર અને બિલિંગ — બધું એક જગ્યાએ.",
    "hero.available": "ગુજરાતી, हिंदी અને English માં ઉપલબ્ધ",
    "hero.startTrial": "મફત ટ્રાયલ શરૂ કરો",
    "hero.watchDemo": "ડેમો જુઓ",
    "hero.stat1Value": "૫,૦૦૦+",
    "hero.stat1Label": "દરજી અમારા પર ભરોસો કરે છે",
    "hero.stat2Value": "૨ મિનિટ",
    "hero.stat2Label": "દરેક ઓર્ડર માટે",
    "hero.stat3Value": "૧૦૦%",
    "hero.stat3Label": "ઓફલાઇન તૈયાર",
    "hero.worksOffline": "ઓફલાઇન કામ કરે છે",
    "hero.noInternet": "ઇન્ટરનેટની જરૂર નથી",
    
    // Features
    "features.badge": "ફીચર્સ",
    "features.title": "તમારા બિઝનેસને",
    "features.titleHighlight": " વધારવા માટે બધું",
    "features.subtitle": "નોટબુક અને રજિસ્ટરને ગુજરાતના દરજી માટે ખાસ ડિઝાઇન કરેલ શક્તિશાળી ડિજિટલ ટૂલ્સથી બદલો.",
    "features.customer": "ગ્રાહક વ્યવસ્થાપન",
    "features.customerDesc": "મોબાઇલ નંબરથી ગ્રાહકોને તરત શોધો. સંપૂર્ણ ઇતિહાસ તમારી આંગળીના ટેરવે.",
    "features.measurements": "સ્માર્ટ માપ",
    "features.measurementsDesc": "શર્ટ, પેન્ટ, કુર્તા, કોટી અને વધુ માટે પૂર્વ-નિર્મિત ટેમ્પલેટ. ફરી ક્યારેય માપ ગુમાવશો નહીં.",
    "features.orders": "ઓર્ડર ટ્રેકિંગ",
    "features.ordersDesc": "કટિંગથી ડિલિવરી સુધી દરેક ઓર્ડરને ટ્રેક કરો. એક નજરમાં જાણો શું પેન્ડિંગ છે.",
    "features.billing": "તાત્કાલિક બિલિંગ",
    "features.billingDesc": "સેકન્ડોમાં પ્રોફેશનલ બિલ બનાવો. પ્રિન્ટ કરો અથવા WhatsApp દ્વારા શેર કરો.",
    "features.offline": "ઓફલાઇન કામ કરે છે",
    "features.languages": "૩ ભાષાઓ",
    "features.whatsapp": "WhatsApp બિલ",
    "features.alerts": "ડિલિવરી એલર્ટ",
    "features.reports": "દૈનિક રિપોર્ટ",
    "features.payments": "ચુકવણી ટ્રેકિંગ",
    "features.mobile": "મોબાઇલ ફ્રેંડલી",
    "features.sync": "ઓટો સિંક",
    "features.more": "અને ઘણું બધું...",
    
    // Workflow
    "workflow.badge": "કેવી રીતે કામ કરે છે",
    "workflow.title": "પરંપરાગત vs.",
    "workflow.titleHighlight": " ડિજિટલ રીત",
    "workflow.subtitle": "જુઓ દરરોજ કેટલો સમય બચાવી શકો છો",
    "workflow.traditional": "પરંપરાગત પદ્ધતિ",
    "workflow.software": "StyleSavvy સાથે",
    "workflow.t1Step": "ગ્રાહક આવે છે",
    "workflow.t1Issue": "જૂની નોટબુક શોધો",
    "workflow.t2Step": "માપ શોધો",
    "workflow.t2Issue": "પાના ફેરવો",
    "workflow.t3Step": "નવો ઓર્ડર લખો",
    "workflow.t3Issue": "અનેક રજિસ્ટર",
    "workflow.t4Step": "બિલ ગણો",
    "workflow.t4Issue": "મેન્યુઅલ ગણતરી",
    "workflow.t5Step": "ડિલિવરી ટ્રેક કરો",
    "workflow.t5Issue": "બધા પાના તપાસો",
    "workflow.s1Step": "મોબાઇલ નંબર દાખલ કરો",
    "workflow.s1Benefit": "તાત્કાલિક શોધ",
    "workflow.s2Step": "બધા માપ જુઓ",
    "workflow.s2Benefit": "ઓટો-લોડ",
    "workflow.s3Step": "ઓર્ડર બનાવો",
    "workflow.s3Benefit": "એક સ્ક્રીન",
    "workflow.s4Step": "બિલ બનાવો",
    "workflow.s4Benefit": "ઓટો-ગણતરી",
    "workflow.s5Step": "સ્ટેટસ ટ્રેક કરો",
    "workflow.s5Benefit": "ડેશબોર્ડ વ્યૂ",
    "workflow.traditionalTime": "૧૬-૨૧ મિનિટ",
    "workflow.softwareTime": "૨ મિનિટથી ઓછી",
    "workflow.perCustomer": "દરેક ગ્રાહક દીઠ (સરેરાશ)",
    "workflow.saveUp": "બચાવો",
    "workflow.saveHours": "૩+ કલાક",
    "workflow.everyDay": "દરરોજ",
    "workflow.customers": "૨૦ ગ્રાહકો સાથે",
    
    // Pricing
    "pricing.badge": "કિંમત",
    "pricing.title": "સરળ, પારદર્શક",
    "pricing.titleHighlight": " કિંમત",
    "pricing.subtitle": "મફતમાં શરૂ કરો, જ્યારે વધુ જરૂર હોય ત્યારે અપગ્રેડ કરો. કોઈ છુપી ફી નથી.",
    "pricing.free": "મફત",
    "pricing.basic": "બેસિક",
    "pricing.professional": "પ્રોફેશનલ",
    "pricing.forever": "કાયમ માટે",
    "pricing.month": "/મહિનો",
    "pricing.freeDesc": "ખરીદતા પહેલા ટ્રાય કરવા માટે પરફેક્ટ",
    "pricing.basicDesc": "વધતી ટેલરિંગ દુકાનો માટે",
    "pricing.proDesc": "સ્થાપિત બિઝનેસ માટે",
    "pricing.getStarted": "શરૂ કરો",
    "pricing.startTrial": "મફત ટ્રાયલ શરૂ કરો",
    "pricing.mostPopular": "સૌથી લોકપ્રિય",
    "pricing.freeF1": "૫૦ ગ્રાહકો સુધી",
    "pricing.freeF2": "બેસિક માપ",
    "pricing.freeF3": "માત્ર લોકલ સ્ટોરેજ",
    "pricing.freeF4": "એક ડિવાઇસ",
    "pricing.basicF1": "અમર્યાદિત ગ્રાહકો",
    "pricing.basicF2": "બધા માપ ટેમ્પલેટ",
    "pricing.basicF3": "ક્લાઉડ બેકઅપ",
    "pricing.basicF4": "WhatsApp ઇન્ટિગ્રેશન",
    "pricing.basicF5": "૨ ડિવાઇસ",
    "pricing.basicF6": "ઇમેઇલ સપોર્ટ",
    "pricing.proF1": "બેસિકમાં બધું",
    "pricing.proF2": "અનેક કારીગર",
    "pricing.proF3": "SMS નોટિફિકેશન",
    "pricing.proF4": "એડવાન્સ રિપોર્ટ",
    "pricing.proF5": "૫ ડિવાઇસ",
    "pricing.proF6": "પ્રાયોરિટી સપોર્ટ",
    "pricing.proF7": "કારીગર વેજ ટ્રેકિંગ",
    "pricing.oneTime": "એક વખતની ચુકવણી પસંદ છે?",
    "pricing.lifetime": "માત્ર આટલામાં લાઇફટાઇમ એક્સેસ મેળવો",
    "pricing.lifetimePrice": "₹૯,૯૯૯",
    "pricing.noMonthly": "(કોઈ માસિક ફી નથી!)",
    "pricing.learnMore": "લાઇફટાઇમ ડીલ વિશે વધુ જાણો",
    
    // Languages Section
    "lang.badge": "બહુ-ભાષા સપોર્ટ",
    "lang.title": "તમારી પોતાની",
    "lang.titleHighlight": "ભાષામાં વાપરો",
    "lang.subtitle": "અમે સમજીએ છીએ કે તમારી માતૃભાષામાં સોફ્ટવેર વાપરવાથી આરામ મળે છે. એટલે StyleSavvy ગુજરાતી, હિન્દી અને અંગ્રેજીમાં સંપૂર્ણ ઉપલબ્ધ છે.",
    "lang.feature1": "બધી ૩ ભાષાઓમાં સંપૂર્ણ UI",
    "lang.feature2": "માપના લેબલ અનુવાદિત",
    "lang.feature3": "મદદ અને ટ્યુટોરિયલ ઉપલબ્ધ",
    "lang.feature4": "ગુજરાતીમાં ગ્રાહક સપોર્ટ",
    "lang.primary": "પ્રાથમિક",
    "lang.gujarati": "ગુજરાતી",
    "lang.hindi": "હિન્દી",
    "lang.english": "અંગ્રેજી",
    "lang.sampleGu": "તમારા ગ્રાહકોની માપ અને ઓર્ડર સરળતાથી મેનેજ કરો",
    "lang.sampleHi": "अपने ग्राहकों की नाप और ऑर्डर आसानी से प्रबंधित करें",
    "lang.sampleEn": "Easily manage your customers' measurements and orders",
    
    // CTA
    "cta.title": "તમારા ટેલરિંગ બિઝનેસને",
    "cta.titleHighlight": "ટ્રાન્સફોર્મ કરવા તૈયાર છો?",
    "cta.subtitle": "સુરતના હજારો દરજીઓ સાથે જોડાઓ જેમણે પહેલેથી સ્વિચ કર્યું છે. આજે જ તમારી મફત ટ્રાયલ શરૂ કરો — કોઈ ક્રેડિટ કાર્ડ જરૂરી નથી.",
    "cta.trial": "૧૪-દિવસની મફત ટ્રાયલ શરૂ કરો",
    "cta.contact": "સેલ્સનો સંપર્ક કરો",
    "cta.whatsapp": "WhatsApp સપોર્ટ ઉપલબ્ધ",
    
    // Footer
    "footer.tagline": "ગુજરાત અને તેની બહારના આધુનિક ટેલરિંગ બિઝનેસ માટે બનાવેલ સંપૂર્ણ દરજી મેનેજમેન્ટ સોફ્ટવેર.",
    "footer.taglineGu": "ગુજરાતના દરજીઓ માટે સંપૂર્ણ સોફ્ટવેર",
    "footer.product": "પ્રોડક્ટ",
    "footer.support": "સપોર્ટ",
    "footer.company": "કંપની",
    "footer.features": "ફીચર્સ",
    "footer.pricing": "કિંમત",
    "footer.howItWorks": "કેવી રીતે કામ કરે છે",
    "footer.downloadApp": "એપ ડાઉનલોડ કરો",
    "footer.helpCenter": "હેલ્પ સેન્ટર",
    "footer.videoTutorials": "વિડિયો ટ્યુટોરિયલ",
    "footer.contactUs": "અમારો સંપર્ક કરો",
    "footer.whatsappSupport": "WhatsApp સપોર્ટ",
    "footer.aboutUs": "અમારા વિશે",
    "footer.careers": "કરિયર",
    "footer.privacy": "પ્રાઇવસી પોલિસી",
    "footer.terms": "સેવાની શરતો",
    "footer.rights": "© ૨૦૨૪ StyleSavvy. બધા અધિકારો સુરક્ષિત.",
    "footer.madeWith": "સુરતના ટેલરિંગ સમુદાય માટે ❤️ થી બનાવેલ",
  },
  hi: {
    // Navbar
    "nav.features": "फीचर्स",
    "nav.howItWorks": "कैसे काम करता है",
    "nav.pricing": "कीमत",
    "nav.languages": "भाषाएं",
    "nav.login": "लॉग इन",
    "nav.startTrial": "मुफ्त ट्रायल शुरू करें",
    
    // Hero
    "hero.badge": "सूरत के टेलरिंग उद्योग के लिए बनाया गया",
    "hero.title1": "अपने",
    "hero.title2": "टेलरिंग बिज़नेस को",
    "hero.title3": "पहले जैसा कभी नहीं मैनेज करें",
    "hero.subtitle": "आधुनिक दर्जी के लिए पूर्ण सॉफ्टवेयर समाधान। ग्राहक प्रबंधन, माप, ऑर्डर और बिलिंग — सब एक जगह।",
    "hero.available": "ગુજરાતી, हिंदी और English में उपलब्ध",
    "hero.startTrial": "मुफ्त ट्रायल शुरू करें",
    "hero.watchDemo": "डेमो देखें",
    "hero.stat1Value": "5,000+",
    "hero.stat1Label": "दर्जी हम पर भरोसा करते हैं",
    "hero.stat2Value": "2 मिनट",
    "hero.stat2Label": "प्रति ऑर्डर",
    "hero.stat3Value": "100%",
    "hero.stat3Label": "ऑफलाइन रेडी",
    "hero.worksOffline": "ऑफलाइन काम करता है",
    "hero.noInternet": "इंटरनेट की जरूरत नहीं",
    
    // Features
    "features.badge": "फीचर्स",
    "features.title": "आपके बिज़नेस को",
    "features.titleHighlight": " बढ़ाने के लिए सब कुछ",
    "features.subtitle": "नोटबुक और रजिस्टरों को गुजरात के दर्जियों के लिए विशेष रूप से डिज़ाइन किए गए शक्तिशाली डिजिटल टूल्स से बदलें।",
    "features.customer": "ग्राहक प्रबंधन",
    "features.customerDesc": "मोबाइल नंबर से ग्राहकों को तुरंत खोजें। पूरा इतिहास आपकी उंगलियों पर।",
    "features.measurements": "स्मार्ट माप",
    "features.measurementsDesc": "शर्ट, पैंट, कुर्ता, कोटी और अधिक के लिए पूर्व-निर्मित टेम्पलेट। फिर कभी माप न खोएं।",
    "features.orders": "ऑर्डर ट्रैकिंग",
    "features.ordersDesc": "कटिंग से डिलीवरी तक हर ऑर्डर को ट्रैक करें। एक नज़र में जानें क्या पेंडिंग है।",
    "features.billing": "तत्काल बिलिंग",
    "features.billingDesc": "सेकंडों में प्रोफेशनल बिल बनाएं। प्रिंट करें या WhatsApp से शेयर करें।",
    "features.offline": "ऑफलाइन काम करता है",
    "features.languages": "3 भाषाएं",
    "features.whatsapp": "WhatsApp बिल",
    "features.alerts": "डिलीवरी अलर्ट",
    "features.reports": "दैनिक रिपोर्ट",
    "features.payments": "भुगतान ट्रैकिंग",
    "features.mobile": "मोबाइल फ्रेंडली",
    "features.sync": "ऑटो सिंक",
    "features.more": "और भी बहुत कुछ...",
    
    // Workflow
    "workflow.badge": "कैसे काम करता है",
    "workflow.title": "पारंपरिक vs.",
    "workflow.titleHighlight": " डिजिटल तरीका",
    "workflow.subtitle": "देखें हर दिन कितना समय बचा सकते हैं",
    "workflow.traditional": "पारंपरिक तरीका",
    "workflow.software": "StyleSavvy के साथ",
    "workflow.t1Step": "ग्राहक आता है",
    "workflow.t1Issue": "पुरानी नोटबुक खोजो",
    "workflow.t2Step": "माप खोजो",
    "workflow.t2Issue": "पेज पलटो",
    "workflow.t3Step": "नया ऑर्डर लिखो",
    "workflow.t3Issue": "कई रजिस्टर",
    "workflow.t4Step": "बिल की गणना करो",
    "workflow.t4Issue": "मैन्युअल गणना",
    "workflow.t5Step": "डिलीवरी ट्रैक करो",
    "workflow.t5Issue": "सभी पेज जांचो",
    "workflow.s1Step": "मोबाइल नंबर दर्ज करें",
    "workflow.s1Benefit": "तत्काल खोज",
    "workflow.s2Step": "सभी माप देखें",
    "workflow.s2Benefit": "ऑटो-लोड",
    "workflow.s3Step": "ऑर्डर बनाएं",
    "workflow.s3Benefit": "एक स्क्रीन",
    "workflow.s4Step": "बिल बनाएं",
    "workflow.s4Benefit": "ऑटो-गणना",
    "workflow.s5Step": "स्टेटस ट्रैक करें",
    "workflow.s5Benefit": "डैशबोर्ड व्यू",
    "workflow.traditionalTime": "16-21 मिनट",
    "workflow.softwareTime": "2 मिनट से कम",
    "workflow.perCustomer": "प्रति ग्राहक (औसत)",
    "workflow.saveUp": "बचाएं",
    "workflow.saveHours": "3+ घंटे",
    "workflow.everyDay": "हर दिन",
    "workflow.customers": "20 ग्राहकों के साथ",
    
    // Pricing
    "pricing.badge": "कीमत",
    "pricing.title": "सरल, पारदर्शी",
    "pricing.titleHighlight": " कीमत",
    "pricing.subtitle": "मुफ्त में शुरू करें, जब ज़्यादा चाहिए तब अपग्रेड करें। कोई छुपी फीस नहीं।",
    "pricing.free": "मुफ्त",
    "pricing.basic": "बेसिक",
    "pricing.professional": "प्रोफेशनल",
    "pricing.forever": "हमेशा के लिए",
    "pricing.month": "/महीना",
    "pricing.freeDesc": "खरीदने से पहले ट्राय करने के लिए परफेक्ट",
    "pricing.basicDesc": "बढ़ती टेलरिंग दुकानों के लिए",
    "pricing.proDesc": "स्थापित बिज़नेस के लिए",
    "pricing.getStarted": "शुरू करें",
    "pricing.startTrial": "मुफ्त ट्रायल शुरू करें",
    "pricing.mostPopular": "सबसे लोकप्रिय",
    "pricing.freeF1": "50 ग्राहकों तक",
    "pricing.freeF2": "बेसिक माप",
    "pricing.freeF3": "केवल लोकल स्टोरेज",
    "pricing.freeF4": "एक डिवाइस",
    "pricing.basicF1": "असीमित ग्राहक",
    "pricing.basicF2": "सभी माप टेम्पलेट",
    "pricing.basicF3": "क्लाउड बैकअप",
    "pricing.basicF4": "WhatsApp इंटीग्रेशन",
    "pricing.basicF5": "2 डिवाइस",
    "pricing.basicF6": "ईमेल सपोर्ट",
    "pricing.proF1": "बेसिक में सब कुछ",
    "pricing.proF2": "कई कारीगर",
    "pricing.proF3": "SMS नोटिफिकेशन",
    "pricing.proF4": "एडवांस रिपोर्ट",
    "pricing.proF5": "5 डिवाइस",
    "pricing.proF6": "प्राथमिकता सपोर्ट",
    "pricing.proF7": "कारीगर वेतन ट्रैकिंग",
    "pricing.oneTime": "एक बार भुगतान पसंद है?",
    "pricing.lifetime": "केवल इतने में लाइफटाइम एक्सेस पाएं",
    "pricing.lifetimePrice": "₹9,999",
    "pricing.noMonthly": "(कोई मासिक शुल्क नहीं!)",
    "pricing.learnMore": "लाइफटाइम डील के बारे में और जानें",
    
    // Languages Section
    "lang.badge": "बहु-भाषा सपोर्ट",
    "lang.title": "अपनी",
    "lang.titleHighlight": "भाषा में उपयोग करें",
    "lang.subtitle": "हम समझते हैं कि अपनी मातृभाषा में सॉफ्टवेयर का उपयोग करना आरामदायक है। इसलिए StyleSavvy गुजराती, हिंदी और अंग्रेजी में पूरी तरह उपलब्ध है।",
    "lang.feature1": "सभी 3 भाषाओं में पूर्ण UI",
    "lang.feature2": "माप लेबल अनुवादित",
    "lang.feature3": "मदद और ट्यूटोरियल उपलब्ध",
    "lang.feature4": "गुजराती में ग्राहक सपोर्ट",
    "lang.primary": "प्राथमिक",
    "lang.gujarati": "गुजराती",
    "lang.hindi": "हिंदी",
    "lang.english": "अंग्रेज़ी",
    "lang.sampleGu": "તમારા ગ્રાહકોની માપ અને ઓર્ડર સરળતાથી મેનેજ કરો",
    "lang.sampleHi": "अपने ग्राहकों की नाप और ऑर्डर आसानी से प्रबंधित करें",
    "lang.sampleEn": "Easily manage your customers' measurements and orders",
    
    // CTA
    "cta.title": "अपने टेलरिंग बिज़नेस को",
    "cta.titleHighlight": "ट्रांसफॉर्म करने के लिए तैयार?",
    "cta.subtitle": "सूरत के हज़ारों दर्जियों से जुड़ें जिन्होंने पहले ही स्विच किया है। आज ही अपना मुफ्त ट्रायल शुरू करें — कोई क्रेडिट कार्ड ज़रूरी नहीं।",
    "cta.trial": "14-दिन का मुफ्त ट्रायल शुरू करें",
    "cta.contact": "सेल्स से संपर्क करें",
    "cta.whatsapp": "WhatsApp सपोर्ट उपलब्ध",
    
    // Footer
    "footer.tagline": "गुजरात और उससे आगे के आधुनिक टेलरिंग बिज़नेस के लिए बनाया गया पूर्ण दर्जी प्रबंधन सॉफ्टवेयर।",
    "footer.taglineGu": "गुजरात के दर्जियों के लिए पूर्ण सॉफ्टवेयर",
    "footer.product": "प्रोडक्ट",
    "footer.support": "सपोर्ट",
    "footer.company": "कंपनी",
    "footer.features": "फीचर्स",
    "footer.pricing": "कीमत",
    "footer.howItWorks": "कैसे काम करता है",
    "footer.downloadApp": "ऐप डाउनलोड करें",
    "footer.helpCenter": "हेल्प सेंटर",
    "footer.videoTutorials": "वीडियो ट्यूटोरियल",
    "footer.contactUs": "हमसे संपर्क करें",
    "footer.whatsappSupport": "WhatsApp सपोर्ट",
    "footer.aboutUs": "हमारे बारे में",
    "footer.careers": "करियर",
    "footer.privacy": "प्राइवेसी पॉलिसी",
    "footer.terms": "सेवा की शर्तें",
    "footer.rights": "© 2024 StyleSavvy. सर्वाधिकार सुरक्षित।",
    "footer.madeWith": "सूरत के टेलरिंग समुदाय के लिए ❤️ से बनाया",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
